"""initial_schema

Revision ID: 3e86fcd591d7
Revises: 
Create Date: 2026-07-09 19:36:07.540531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e86fcd591d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carbon_projects', 'verification_cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(3000.0)'))
    op.alter_column('carbon_projects', 'buffer_pool_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
    op.alter_column('carbon_projects', 'vesting_end_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('carbon_projects', 'requires_soil_sample',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('carbon_projects', 'additionality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('carbon_projects', 'available_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('carbon_projects', 'locked_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.create_index(op.f('ix_harvest_tokens_crop_cycle_id'), 'harvest_tokens', ['crop_cycle_id'], unique=False)
    op.drop_column('plots', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('last_updated', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_harvest_tokens_crop_cycle_id'), table_name='harvest_tokens')
    op.alter_column('carbon_projects', 'locked_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('carbon_projects', 'available_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('carbon_projects', 'additionality_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('carbon_projects', 'requires_soil_sample',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('carbon_projects', 'vesting_end_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('carbon_projects', 'buffer_pool_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
    op.alter_column('carbon_projects', 'verification_cost_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(3000.0)'))
    # ### end Alembic commands ###
