"""schema_with_naming_convention

Revision ID: bd897e410c78
Revises: 
Create Date: 2026-09-13 23:23:27.511961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd897e410c78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_carbon_evidence')
    with op.batch_alter_table('carbon_evidence', schema=None) as batch_op:
        batch_op.alter_column('local_file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('carbon_projects', schema=None) as batch_op:
        batch_op.alter_column('verification_cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(3000.0)'))
        batch_op.alter_column('buffer_pool_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
        batch_op.alter_column('vesting_end_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('requires_soil_sample',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('additionality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('available_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('locked_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_column('enrollment_ndvi_reason')
        batch_op.drop_column('enrollment_ndvi')
        batch_op.drop_column('enrollment_ndvi_rejected')

    with op.batch_alter_table('carbon_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_carbon_tokens_retirement_certificate_id'), ['retirement_certificate_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_carbon_tokens_retirement_hash'), ['retirement_hash'])

    with op.batch_alter_table('credit_purchases', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_credit_purchases_certificate_id'), ['certificate_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_credit_purchases_razorpay_payment_id'), ['razorpay_payment_id'])

    with op.batch_alter_table('farmer_kyc', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_farmer_kyc_user_id'), ['user_id'])

    with op.batch_alter_table('harvest_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_tokens_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_harvest_tokens_token_hash'), ['token_hash'])

    with op.batch_alter_table('management_practice_logs', schema=None) as batch_op:
        batch_op.alter_column('local_photo_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('fertilizer_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('fertilizer_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('irrigation_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('yield_tonnes_ha',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('residue_management',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('soil_sample_records', schema=None) as batch_op:
        batch_op.alter_column('lab_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('lab_accreditation_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('collection_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('lab_certificate_local',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('verified_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('admin_soc_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('admin_bulk_density',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('admin_ph',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('admin_nitrogen_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('admin_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('lab_report_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_soil_sample_records_lab_report_hash'), ['lab_report_hash'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_soil_sample_records_qr_bag_id_soil_qr_bags'), 'soil_qr_bags', ['qr_bag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_sample_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_soil_sample_records_qr_bag_id_soil_qr_bags'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_soil_sample_records_lab_report_hash'))
        batch_op.alter_column('lab_report_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rejection_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_nitrogen_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('admin_ph',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('admin_bulk_density',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('admin_soc_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('verified_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lab_certificate_local',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('collection_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lab_accreditation_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lab_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('management_practice_logs', schema=None) as batch_op:
        batch_op.alter_column('residue_management',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('yield_tonnes_ha',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('irrigation_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fertilizer_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fertilizer_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('local_photo_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('harvest_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_harvest_tokens_token_hash'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_harvest_tokens_crop_cycle_id'))

    with op.batch_alter_table('farmer_kyc', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_farmer_kyc_user_id'), type_='unique')

    with op.batch_alter_table('credit_purchases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_credit_purchases_razorpay_payment_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_credit_purchases_certificate_id'), type_='unique')

    with op.batch_alter_table('carbon_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_carbon_tokens_retirement_hash'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_carbon_tokens_retirement_certificate_id'), type_='unique')

    with op.batch_alter_table('carbon_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_ndvi_rejected', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('enrollment_ndvi', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_ndvi_reason', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('locked_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('available_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('additionality_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('requires_soil_sample',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('vesting_end_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('buffer_pool_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(15.0)'))
        batch_op.alter_column('verification_cost_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(3000.0)'))

    with op.batch_alter_table('carbon_evidence', schema=None) as batch_op:
        batch_op.alter_column('local_file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_carbon_evidence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('geo_lat', sa.FLOAT(), nullable=True),
    sa.Column('geo_lng', sa.FLOAT(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('evidence_hash', sa.VARCHAR(), nullable=True),
    sa.Column('exif_lat', sa.FLOAT(), nullable=True),
    sa.Column('exif_lng', sa.FLOAT(), nullable=True),
    sa.Column('exif_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('exif_device', sa.VARCHAR(), nullable=True),
    sa.Column('exif_suspicious', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('gps_distance_m', sa.FLOAT(), nullable=True),
    sa.Column('gps_valid', sa.BOOLEAN(), nullable=True),
    sa.Column('ai_status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('ai_confidence', sa.FLOAT(), nullable=True),
    sa.Column('ai_analysis', sa.TEXT(), nullable=True),
    sa.Column('ai_rejection_reason', sa.VARCHAR(), nullable=True),
    sa.Column('ai_screened_at', sa.DATETIME(), nullable=True),
    sa.Column('review_status', sa.VARCHAR(), server_default=sa.text("'awaiting_ai'"), nullable=True),
    sa.Column('l1_reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('l1_reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('l1_notes', sa.TEXT(), nullable=True),
    sa.Column('l2_reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('l2_reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('l2_notes', sa.TEXT(), nullable=True),
    sa.Column('local_file_path', sa.VARCHAR(), nullable=True),
    sa.Column('tx_hash', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['carbon_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
